name: Automatisation des tests

on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@v3.21.3

      - name: Create Build Directory
        run: mkdir build

      - name: Change to Build Directory
        run: cd build

      - name: Configure CMake Project
        run: cmake ..

      - name: Build Project
        run: cmake --build .

  Test_Add:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Add Test
        run: |
          mkdir build
          cd build
          cmake ..
          ctest -R t1

  Test_Sub:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Sub Test
        run: |
          mkdir build
          cd build
          cmake ..
          ctest -R t2

  Test_Mul:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Mul Test
        run: |
          mkdir build
          cd build
          cmake ..
          ctest -R t3

  Test_Div:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Div Test
        run: |
          mkdir build
          cd build
          cmake ..
          ctest -R t4
  Test_Square:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Square Test
        run: |
          mkdir build
          cd build
          cmake ..
          ctest -R t5